<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教师管理",
                        "menuJump":"列表",
                        "tableName":"jiaoshi"
                    }
                ],
                "menu":"教师管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"在线学习管理",
			            "menuJump":"列表",
			            "tableName":"zaixianxuexi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"在线学习留言管理",
			            "menuJump":"列表",
			            "tableName":"zaixianxuexiLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"在线学习收藏管理",
			            "menuJump":"列表",
			            "tableName":"zaixianxuexiCollection"
			        }
			    ],
			    "menu":"在线学习管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"上交作业管理",
			            "menuJump":"列表",
			            "tableName":"shangjiao"
			        }
			    ],
			    "menu":"上交作业管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"课程管理",
                        "menuJump":"列表",
                        "tableName":"kechng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"课程留言管理",
                        "menuJump":"列表",
                        "tableName":"kechngLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"课程收藏管理",
                        "menuJump":"列表",
                        "tableName":"kechngCollection"
                    }
                ],
                "menu":"课程管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryKechng"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"新闻类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言板管理",
                        "menuJump":"列表",
                        "tableName":"messages"
                    }
                ],
                "menu":"留言板管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"新闻管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"新闻管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"在线学习管理",
			            "menuJump":"列表",
			            "tableName":"zaixianxuexi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"在线学习留言管理",
			            "menuJump":"列表",
			            "tableName":"zaixianxuexiLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"在线学习收藏管理",
			            "menuJump":"列表",
			            "tableName":"zaixianxuexiCollection"
			        }
			    ],
			    "menu":"在线学习管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"上交作业管理",
			            "menuJump":"列表",
			            "tableName":"shangjiao"
			        }
			    ],
			    "menu":"上交作业管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"课程管理",
	                    "menuJump":"列表",
	                    "tableName":"kechng"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"课程留言管理",
	                    "menuJump":"列表",
	                    "tableName":"kechngLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"课程收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"kechngCollection"
	                }
	            ],
	            "menu":"课程管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"留言板管理",
	                    "menuJump":"列表",
	                    "tableName":"messages"
	                }
	            ],
	            "menu":"留言板管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"新闻管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"学生",
	    "tableName":"yonghu"
	}
	,
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改"
			            ],
			            "menu":"在线学习管理",
			            "menuJump":"列表",
			            "tableName":"zaixianxuexi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
							"修改"
			            ],
			            "menu":"在线学习留言管理",
			            "menuJump":"列表",
			            "tableName":"zaixianxuexiLiuyan"
			        }
			       
			    ],
			    "menu":"在线学习管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"上交作业管理",
			            "menuJump":"列表",
			            "tableName":"shangjiao"
			        }
			    ],
			    "menu":"上交作业管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"课程管理",
	                    "menuJump":"列表",
	                    "tableName":"kechng"
	                }
	                ,
	                {
	                    "buttons":[
							"修改",
	                        "查看"
	                    ],
	                    "menu":"课程留言管理",
	                    "menuJump":"列表",
	                    "tableName":"kechngLiuyan"
	                }
	                
	            ],
	            "menu":"课程管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryKechng"
			        }
			
			    ],
			    "menu":"类型管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"修改"
	                    ],
	                    "menu":"留言板管理",
	                    "menuJump":"列表",
	                    "tableName":"messages"
	                }
	            ],
	            "menu":"留言板管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"新闻管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	}
];

var hasMessage = '';
